# Important that the file_name starts with capital letter and has no symbols
# Also recommended not to have other capital letters

# Request
int32 goal
---
# Result
bool succeeded
---
# Feedback
int32[] sequence
